repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.87.1  # Use the latest version
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_docs
        args:
          - --args=--lockfile=false
      - id: terraform_tflint
        args:
          - --args=--enable-rule=terraform_documented_variables
          - --args=--enable-rule=terraform_documented_outputs
      - id: terraform_validate
        args:
          - --hook-config=--retry-once-with-cleanup=true
      - id: terraform_checkov
        args:
          - --args=--quiet
          - --args=--framework=terraform
      - id: terrascan
        args:
          - --args=-i terraform
          - --args=--non-recursive
      - id: tfupdate
        args:
          - --args=provider azurerm

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.1  # Use the latest version
    hooks:
      - id: gitleaks
